notifications:
  slack: bmesipbd2k:9FsEwo783y455NkXSkbYyj6Z
    secure: LAR/qC6t4bn9br9AyEwYY7MO3vrmMxIZwoY4H8UygVs6QcfoEPqnM6TaclKIw94u6VgrIpvsT+FCK8sIaUcoCCQu6j4UpZy8StRRrNEsKzyDwH3LoGnHciiiQS+wqoXdlQv4ZqDmXGU34hqApxX1k2IoIYsPd7y5GNjhpSPLNHZUrAGcA/M9QaZMhqM55SvtZE995b4cHrnCml9mP4nahyPwufDolDxLksruZxtGy6xe0ASMpuzeQN7v5rsJa3HbTXQsDH4LOns5kva87l4wALqZ9Ibz540GaU1mB6znVjXDNxl5GgWWZg840gFG6Q6ajwQFFBc4qw84Mf+V/B7HxPfOAiO3UorbrViSAMs1BTioYN0oSl72ggPUSZeFaDU/SSyTtFcEJRXQGXKUB2XEZSlb8tiG8Yi6cbUCnFoCurX+vsHPd3BZanKww4qpuwhR7T2+DEQvYWyxXd5T5Q6T/zKxSw1P8Az8i00rzsjvOriILpkd0AvTzi5pHQtxvoNF8Qe9g2XSB9R1wTvx874+N5mMY4U+WUd9PJD+aQYoPDCORlql3OJlYhAR2wAqa0pZGLf5kFYNqK3tg5aWljijp0/JpiMER+1NihrnsAtJwkmFjDmbk4iSwlKejjSrIHb/ec+Ro/n6jUsmWc7zckdb38ptrJFpnp+gkEmHsQ8jXs0=

  email: false
language: python
dist: xenial
cache: false
before_install:
- python --version
- uname -a
install:
- python setup.py install
script:
- python tests/variant_call_tests.py
